env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
rules:
  '@typescript-eslint/indent': off
  'arrow-parens': off
  'function-paren-newline': off
  'implicit-arrow-linebreak': off
  'import/prefer-default-export': off
  import/no-extraneous-dependencies: ["error", {"devDependencies": ["**/*.test.ts", "src/tests/**/*.ts"]}]
  'no-confusing-arrow': off
  'object-curly-newline': off
  'operator-linebreak': off
  'simple-import-sort/imports': error
