env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  import/prefer-default-export: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.test.ts'
        - 'src/tests/**/*.ts'
  prettier/prettier: error
