version: '3.8'
services:
  db:
    image: postgres:11.4
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "nodeTemplateDB"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db:
