x-common: &common
  image: "node:18.16.1"
  environment:
    - BASE_URL=http://dummy-server
    - NODE_ENV=test
    - PORT=1111
    - LOG_LEVEL=info
    - DATABASE_URL=postgres://dbuser:dbpass@localhost:dbport/dbname
    - ACCESS_TOKEN_SECRET=secret
    - REFRESH_TOKEN_SECRET=secret
    - ACCESS_TOKEN_EXPIRES_IN=1d
    - REFRESH_TOKEN_EXPIRES_IN=1d
    - EMAIL_CLIENT='test-client'
    - EMAIL_SERVICE_PROVIDER_USER_ID='test'
    - EMAIL_SERVICE_PROVIDER_USER_PASSWORD='test'
    - EMAIL_HOST='test'
    - EMAIL_PORT=1111
    - APP_NAME='APPNAME'

pipeline:
  setup:
    <<: *common
    commands:
      - npm ci --prefer-offline
  js-lint:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run lint
  js-test:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run test
  build:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run build
